version: '3.1'

services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    #env_file:
    #  - .env
    container_name: solucao-carrefour-api
    restart: always
    ports:
      - 80:3000
  db:
    container_name: solucao-carrefour-mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: